name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1

      - run: deno --version
      - run: deno fmt --check
      - run: deno lint --unstable
