name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master

      - name: Log versions
        run: deno --version

      - name: Run deno fmt
        run: deno fmt --check

      - name: Run deno lint
        run: deno lint --unstable
