name: Update weibo heat news

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 9 * * *' # Everydat at 09:00

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup yarn
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run Script
        run: |
          node index

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          enable_jekyll: true
